version: "3.7"

networks:
  default:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}

services:
  redis:
    image: redis
    networks:
      - default

  gcc-medical-tracker:
    image: ${REGISTRY}/${IMAGETAG}:${GO_REVISION}
    env_file: env_vars/${GO_STAGE_NAME}.env
