stackname: medicaltracker
env_folder: env_vars
replicas:
  dev: 1
  qa: 1 
  uat: 1
  prod: 3
restart_policy: any
max_mem: 1024M
max_cpu: 1
traefik_application_port: 4004
traefik_https_enable: true
traefik_ssl_provider: letsencrypt
vault:
  enabled: true
  name: gcc_medical_tracker_be   
  dev:
    - DB_PORT
    - DB_NAME
    - DB_HOST
    - DB_USER
    - ENABLE_SSL
    - REDIS_HOST
    - AUTH_KEY
    - DB_PWD
    - NODE_ENV
  prod:
    - DB_PORT
    - DB_NAME
    - DB_HOST
    - DB_USER
    - ENABLE_SSL
    - REDIS_HOST
    - AUTH_KEY
    - DB_PWD
    - NODE_ENV
